stages:
  - build_and_deploy

build_and_deploy:
  stage: build_and_deploy
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  tags:
    - diar-admin-web
  script:

    - docker stop diar_admin_web || true
    - docker rm diar_admin_web || true
    - docker rmi -f diar_admin_web || true
    - docker build -t diar_admin_web:latest .
    - docker run -d --name diar_admin_web -p 4173:4173 diar_admin_web:latest
  only:
    - adinai
